#!/usr/bin/env bash
# Displays a list of currently running processes
# Must show all processes, for all users
# Including those which might not have a TTY
# Display in a user-oriented format
# Show process hierarchy

ps -a -x -u -f
